import {LayoutSetting} from "@/layout/types.ts";
export default {
  title: 'Antdv Pro',
  theme: "inverted",
  logo: '/logo.svg',
  collapsed: false,
  drawerVisible: false,
  colorPrimary: '#1677FF',
  layout: 'side',
  showLogo: true,
  contentWidth: 'Fluid',
  fixedHeader: true,
  splitMenus: false,
  header: true,
  menu: true,
  menuHeader: true,
  footer: false,
  colorWeak: false,
  multiTab: true,
  multiTabFixed: false,
  keepAlive: true,
  accordionMode: true,
  leftCollapsed: false,
  headerHeight: 48,
  copyright: 'Antdv Pro Team 2023',
  animationName: 'slide-fadein-right',
} as LayoutSetting